// codeCommitment.ts — GENERATED by scripts/gen-codecommit.mjs. DO NOT EDIT BY HAND.
//
// The PoCA code identity: a single sha256 pinning the exact src tree (trader-worker/src + fly-brain/src)
// + FlyWire connectome artifact + grey-release knob DEFAULTS this Worker was built from. Regenerated on
// every deploy (the codegen step runs before wrangler). A change to ANY hashed source file or the artifact
// rotates CODE_COMMITMENT, which forces the running PoCA epoch to seal and a new one to open (admin
// kind=7 CODE_CHANGE) — so a silent code swap is a permanent, on-chain-visible break in the agency chain.
// codeCommitment.ts is excluded from its own tree hash. git HEAD is NOT an input (see GIT_COMMIT below).

/** The git commit this build was generated from (“unknown” when git was unavailable at codegen time).
 *  Informational only — NOT folded into CODE_COMMITMENT (a source-neutral commit must not rotate it). */
export const GIT_COMMIT = "eb42670aa549312021998a94f1390c4be7953f14";

/** sha256(src tree hash + canonical knob defaults + FlyWire artifact hash) — the PoCA code identity (64 lowercase hex). */
export const CODE_COMMITMENT = "7706328c24a5455fb0f95b8e40b9ddeb98c721773549030e670349736893225d";

/** A non-secret summary of what fed CODE_COMMITMENT, for the /poca read-out + offline recompute. */
export const CODE_COMMITMENT_INPUTS = {
  "treeHash": "33cad5964d72d99b8bf384573805e7f24a49c6ef5756f0b19427cc4e8a41a621",
  "fileCount": 140,
  "knobCount": 21,
  "artifactHash": "dc84edfc2cd6cc6a0fcba671e2bd265423cfd7905e5d0e19bd183925c4377544"
} as const;
