//! Verbatim ports of the transcendental functions V8 12.4 (Node 22) evaluates `Math.*` with, so
//! every last bit matches the TypeScript reference:
//!
//! * `exp`, `log`, `expm1`, `tanh` — fdlibm as shipped in `v8/src/base/ieee754.cc`
//!   (tag 12.4.254.21). Rust's `f64::exp/ln` call the platform libm (Apple's on macOS) and the
//!   `libm` crate carries musl's rewrites of `log`/`tanh`; both differ from V8 by 1 ULP on ~1–2 %
//!   of inputs (measured against tests/fixtures/mathfns.json), which is fatal for bit parity.
//! * `cos` (+ `sin`) — fdlibm too (`__kernel_cos`, `__kernel_sin`, `__ieee754_rem_pio2`,
//!   `__kernel_rem_pio2`). Upstream V8 can swap in glibc's IBM sin/cos via
//!   V8_USE_LIBM_TRIG_FUNCTIONS, but Node's build does not (verified against the fixture: a glibc
//!   port disagreed on ~2 % of inputs, the contracted fdlibm port agrees on all).
//!
//! FMA CONTRACTION. The reference Node 22 arm64 binary was compiled by clang with its default
//! `-ffp-contract=on` (clang User's Manual: "fuse within a statement, as the language standard
//! permits"; Node's gyp build adds no `-ffp-contract=off`), and AArch64 has fused multiply-add in
//! its base ISA (FMADD/FMSUB/FNMSUB), so inside each C/C++ expression every `a*b + c` /
//! `a*b - c` / `c - a*b` whose multiply is a temporary became ONE fused multiply-add (single
//! rounding). Rust never contracts, so those spots are written with `f64::mul_add` explicitly and
//! each one carries a comment quoting the fdlibm expression it fuses. The rule applied at every
//! site is clang's: fuse only within one expression; when both operands of a `+`/`-` are products,
//! the LEFT one fuses and the right one is rounded first; a product that is stored to a named
//! variable first is never fused with a later use. Evidence: without the fusions `log`/`expm1`/
//! `cos` differ from Node by 1 ULP on ~2 % of `tests/fixtures/mathfns.json`; with them every
//! sampled value matches (tests/parity.rs `math_*`).
//!
//! The same fixtures regenerated by the x86-64 Node 22.22.0 build (run under Rosetta, where
//! baseline x86-64 codegen has no FMA instruction so clang cannot contract) differ from the arm64
//! ones by 1 ULP on 70/4000 `log`, 24/4000 `cos` and 2/6012 `tanh` samples and on ~0.2 % of the
//! f64 connectome weights — and the un-fused fdlibm code reproduces THOSE bits. `exp`/`sqrt` are
//! identical on both. Because `LifNetwork` stores weights as f32, none of those weight differences
//! survive the rounding, and the dynamics fixtures are byte-identical across the two builds.

// fdlibm/glibc idioms that clippy dislikes: literal constants (E, 2/pi, log2 e) written the way the
// reference writes them, and `x - x` / `x / x` used to produce NaN with the right sign bits.
#![allow(
    clippy::excessive_precision,
    clippy::many_single_char_names,
    clippy::needless_late_init,
    clippy::approx_constant,
    clippy::eq_op,
    clippy::needless_range_loop,
    clippy::explicit_counter_loop,
    clippy::neg_cmp_op_on_partial_ord,
    clippy::manual_clamp
)]

/// The contraction point. With the `fma` feature (default) this is one fused multiply-add,
/// matching Node builds whose compiler contracted `a*b + c` (AArch64, where FMA is in the base
/// ISA); without it, it is the plain two-rounding `a * b + c`, matching baseline x86-64 Node
/// builds, where clang has no FMA instruction to contract to. Every call site quotes the fdlibm
/// expression it stands for. Sign flips used to express `x - a*b` as `fma(-a, b, x)` are exact,
/// so the unfused form is bit-identical to the un-contracted C.
#[inline(always)]
fn fma(a: f64, b: f64, c: f64) -> f64 {
    #[cfg(feature = "fma")]
    {
        a.mul_add(b, c)
    }
    #[cfg(not(feature = "fma"))]
    {
        a * b + c
    }
}

#[inline]
fn high_word(x: f64) -> u32 {
    (x.to_bits() >> 32) as u32
}
#[inline]
fn low_word(x: f64) -> u32 {
    x.to_bits() as u32
}
#[inline]
fn insert_words(hi: u32, lo: u32) -> f64 {
    f64::from_bits(((hi as u64) << 32) | lo as u64)
}
#[inline]
fn set_high_word(x: f64, hi: u32) -> f64 {
    f64::from_bits((x.to_bits() & 0x0000_0000_FFFF_FFFF) | ((hi as u64) << 32))
}

// ------------------------------------------------------------------------------------ exp (fdlibm e_exp.c)

pub fn exp(mut x: f64) -> f64 {
    const ONE: f64 = 1.0;
    const HALF: [f64; 2] = [0.5, -0.5];
    const O_THRESHOLD: f64 = 7.09782712893383973096e+02;
    const U_THRESHOLD: f64 = -7.45133219101941108420e+02;
    const LN2HI: [f64; 2] = [6.93147180369123816490e-01, -6.93147180369123816490e-01];
    const LN2LO: [f64; 2] = [1.90821492927058770002e-10, -1.90821492927058770002e-10];
    const INVLN2: f64 = 1.44269504088896338700e+00;
    const P1: f64 = 1.66666666666666019037e-01;
    const P2: f64 = -2.77777777770155933842e-03;
    const P3: f64 = 6.61375632143793436117e-05;
    const P4: f64 = -1.65339022054652515390e-06;
    const P5: f64 = 4.13813679705723846039e-08;
    const E: f64 = 2.718281828459045;
    const HUGE: f64 = 1.0e+300;
    const TWOM1000: f64 = 9.33263618503218878990e-302;
    const TWO1023: f64 = 8.988465674311579539e307;

    let mut hi = 0.0f64;
    let mut lo = 0.0f64;
    let mut k: i32 = 0;
    let mut hx = high_word(x);
    let xsb = ((hx >> 31) & 1) as usize;
    hx &= 0x7FFF_FFFF;

    if hx >= 0x4086_2E42 {
        if hx >= 0x7FF0_0000 {
            let lx = low_word(x);
            if ((hx & 0xFFFFF) | lx) != 0 {
                return x + x;
            } else {
                return if xsb == 0 { x } else { 0.0 };
            }
        }
        if x > O_THRESHOLD {
            return HUGE * HUGE;
        }
        if x < U_THRESHOLD {
            return TWOM1000 * TWOM1000;
        }
    }

    if hx > 0x3FD6_2E42 {
        if hx < 0x3FF0_A2B2 {
            if x == 1.0 {
                return E;
            }
            hi = x - LN2HI[xsb];
            lo = LN2LO[xsb];
            k = 1 - xsb as i32 - xsb as i32;
        } else {
            // invln2 * x + halF[xsb]  →  fma
            k = fma(INVLN2, x, HALF[xsb]) as i32;
            let t = k as f64;
            // x - t * ln2HI[0]  →  fma(-t, ln2HI, x)  (exact either way)
            hi = fma(-t, LN2HI[0], x);
            lo = t * LN2LO[0];
        }
        x = hi - lo;
    } else if hx < 0x3E30_0000 {
        if HUGE + x > ONE {
            return ONE + x;
        }
    } else {
        k = 0;
    }

    let t = x * x;
    let twopk = if k >= -1021 {
        insert_words(0x3FF0_0000u32.wrapping_add((k as u32) << 20), 0)
    } else {
        insert_words(0x3FF0_0000u32.wrapping_add(((k + 1000) as u32) << 20), 0)
    };
    // x - t * (P1 + t * (P2 + t * (P3 + t * (P4 + t * P5))))  →  nested fma
    let c = fma(-t, fma(t, fma(t, fma(t, fma(t, P5, P4), P3), P2), P1), x);
    if k == 0 {
        return ONE - ((x * c) / (c - 2.0) - x);
    }
    let y = ONE - ((lo - (x * c) / (2.0 - c)) - hi);
    if k >= -1021 {
        if k == 1024 {
            return y * 2.0 * TWO1023;
        }
        y * twopk
    } else {
        y * twopk * TWOM1000
    }
}

// ------------------------------------------------------------------------------------ log (fdlibm e_log.c)

pub fn log(mut x: f64) -> f64 {
    const LN2_HI: f64 = 6.93147180369123816490e-01;
    const LN2_LO: f64 = 1.90821492927058770002e-10;
    const TWO54: f64 = 1.80143985094819840000e+16;
    const LG1: f64 = 6.666666666666735130e-01;
    const LG2: f64 = 3.999999999940941908e-01;
    const LG3: f64 = 2.857142874366239149e-01;
    const LG4: f64 = 2.222219843214978396e-01;
    const LG5: f64 = 1.818357216161805012e-01;
    const LG6: f64 = 1.531383769920937332e-01;
    const LG7: f64 = 1.479819860511658591e-01;
    const ZERO: f64 = 0.0;

    let mut hx = high_word(x) as i32;
    let lx = low_word(x);
    let mut k: i32 = 0;

    if hx < 0x0010_0000 {
        if ((hx & 0x7FFF_FFFF) as u32 | lx) == 0 {
            return f64::NEG_INFINITY;
        }
        if hx < 0 {
            return f64::NAN;
        }
        k -= 54;
        x *= TWO54;
        hx = high_word(x) as i32;
    }
    if hx >= 0x7FF0_0000 {
        return x + x;
    }
    k += (hx >> 20) - 1023;
    hx &= 0x000F_FFFF;
    let mut i = (hx + 0x95F64) & 0x10_0000;
    x = set_high_word(x, (hx | (i ^ 0x3FF0_0000)) as u32);
    k += i >> 20;
    let f = x - 1.0;
    if (0x000F_FFFF & (2 + hx)) < 3 {
        if f == ZERO {
            if k == 0 {
                return ZERO;
            } else {
                let dk = k as f64;
                // dk * ln2_hi + dk * ln2_lo  →  fma(dk, ln2_hi, dk * ln2_lo)
                return fma(dk, LN2_HI, dk * LN2_LO);
            }
        }
        // f * f * (0.5 - 0.333.. * f)  →  (f*f) * fma(-0.333.., f, 0.5)
        let r = f * f * fma(-0.33333333333333333f64, f, 0.5);
        if k == 0 {
            return f - r;
        } else {
            let dk = k as f64;
            // dk*ln2_hi - ((R - dk*ln2_lo) - f)  →  fma(dk, ln2_hi, -(fma(-dk, ln2_lo, R) - f))
            return fma(dk, LN2_HI, -(fma(-dk, LN2_LO, r) - f));
        }
    }
    let s = f / (2.0 + f);
    let dk = k as f64;
    let z = s * s;
    i = hx - 0x6147A;
    let w = z * z;
    let j = 0x6B851 - hx;
    // w * (Lg2 + w * (Lg4 + w * Lg6))  →  w * fma(w, fma(w, Lg6, Lg4), Lg2)
    let t1 = w * fma(w, fma(w, LG6, LG4), LG2);
    // z * (Lg1 + w * (Lg3 + w * (Lg5 + w * Lg7)))
    let t2 = z * fma(w, fma(w, fma(w, LG7, LG5), LG3), LG1);
    i |= j;
    let r = t2 + t1;
    if i > 0 {
        let hfsq = 0.5 * f * f;
        if k == 0 {
            // f - (hfsq - s*(hfsq+R))  →  f - fma(-s, hfsq+R, hfsq)
            f - fma(-s, hfsq + r, hfsq)
        } else {
            // dk*ln2_hi - ((hfsq - (s*(hfsq+R) + dk*ln2_lo)) - f)
            //   →  fma(dk, ln2_hi, -((hfsq - fma(s, hfsq+R, dk*ln2_lo)) - f))
            fma(dk, LN2_HI, -((hfsq - fma(s, hfsq + r, dk * LN2_LO)) - f))
        }
    } else if k == 0 {
        // f - s*(f-R)  →  fma(-s, f-R, f)
        fma(-s, f - r, f)
    } else {
        // dk*ln2_hi - ((s*(f-R) - dk*ln2_lo) - f)  →  fma(dk, ln2_hi, -(fma(s, f-R, -(dk*ln2_lo)) - f))
        fma(dk, LN2_HI, -(fma(s, f - r, -(dk * LN2_LO)) - f))
    }
}

// ------------------------------------------------------------------------------------ expm1 (fdlibm s_expm1.c)

pub fn expm1(mut x: f64) -> f64 {
    const ONE: f64 = 1.0;
    const TINY: f64 = 1.0e-300;
    const O_THRESHOLD: f64 = 7.09782712893383973096e+02;
    const LN2_HI: f64 = 6.93147180369123816490e-01;
    const LN2_LO: f64 = 1.90821492927058770002e-10;
    const INVLN2: f64 = 1.44269504088896338700e+00;
    const Q1: f64 = -3.33333333333331316428e-02;
    const Q2: f64 = 1.58730158725481460165e-03;
    const Q3: f64 = -7.93650757867487942473e-05;
    const Q4: f64 = 4.00821782732936239552e-06;
    const Q5: f64 = -2.01099218183624371326e-07;
    const HUGE: f64 = 1.0e+300;

    let mut hx = high_word(x);
    let xsb = hx & 0x8000_0000;
    hx &= 0x7FFF_FFFF;

    if hx >= 0x4043_687A {
        if hx >= 0x4086_2E42 {
            if hx >= 0x7FF0_0000 {
                let low = low_word(x);
                if ((hx & 0xFFFFF) | low) != 0 {
                    return x + x;
                } else {
                    return if xsb == 0 { x } else { -1.0 };
                }
            }
            if x > O_THRESHOLD {
                return HUGE * HUGE;
            }
        }
        if xsb != 0 && x + TINY < 0.0 {
            return TINY - ONE;
        }
    }

    let k: i32;
    let mut c = 0.0f64;
    let hi;
    let lo;
    if hx > 0x3FD6_2E42 {
        if hx < 0x3FF0_A2B2 {
            if xsb == 0 {
                hi = x - LN2_HI;
                lo = LN2_LO;
                k = 1;
            } else {
                hi = x + LN2_HI;
                lo = -LN2_LO;
                k = -1;
            }
        } else {
            // k = invln2 * x + (xsb == 0 ? 0.5 : -0.5)  →  fma (same expression shape as in exp)
            k = fma(INVLN2, x, if xsb == 0 { 0.5 } else { -0.5 }) as i32;
            let t = k as f64;
            // hi = x - t * ln2_hi  →  fma(-t, ln2_hi, x)
            hi = fma(-t, LN2_HI, x);
            lo = t * LN2_LO;
        }
        x = hi - lo;
        c = (hi - x) - lo;
    } else if hx < 0x3C90_0000 {
        let t = HUGE + x;
        return x - (t - (HUGE + x));
    } else {
        k = 0;
    }

    let hfx = 0.5 * x;
    let hxs = x * hfx;
    // one + hxs*(Q1 + hxs*(Q2 + hxs*(Q3 + hxs*(Q4 + hxs*Q5))))  →  nested fma
    let r1 = fma(hxs, fma(hxs, fma(hxs, fma(hxs, fma(hxs, Q5, Q4), Q3), Q2), Q1), ONE);
    // 3.0 - r1 * hfx  →  fma(-r1, hfx, 3.0)
    let t = fma(-r1, hfx, 3.0);
    // hxs * ((r1 - t) / (6.0 - x * t))
    let mut e = hxs * ((r1 - t) / fma(-x, t, 6.0));
    if k == 0 {
        // x - (x * e - hxs)  →  x - fma(x, e, -hxs)
        return x - fma(x, e, -hxs);
    }
    let twopk = insert_words(0x3FF0_0000u32.wrapping_add((k as u32) << 20), 0);
    // (x * (e - c) - c)  →  fma(x, e - c, -c)
    e = fma(x, e - c, -c);
    e -= hxs;
    if k == -1 {
        // 0.5 * (x - e) - 0.5  →  fma(0.5, x - e, -0.5)
        return fma(0.5f64, x - e, -0.5);
    }
    if k == 1 {
        if x < -0.25 {
            return -2.0 * (e - (x + 0.5));
        } else {
            // one + 2.0 * (x - e)  →  fma(2.0, x - e, one)
            return fma(2.0f64, x - e, ONE);
        }
    }
    if k <= -2 || k > 56 {
        let mut y = ONE - (e - x);
        if k == 1024 {
            y = y * 2.0 * 8.98846567431158e+307;
        } else {
            y *= twopk;
        }
        return y - ONE;
    }
    let mut t = ONE;
    let y;
    if k < 20 {
        t = set_high_word(t, 0x3FF0_0000 - (0x20_0000 >> k));
        y = (t - (e - x)) * twopk;
    } else {
        t = set_high_word(t, ((0x3FF - k) as u32) << 20);
        let mut yy = x - (e + t);
        yy += ONE;
        y = yy * twopk;
    }
    y
}

// ------------------------------------------------------------------------------------ tanh (fdlibm s_tanh.c)

pub fn tanh(x: f64) -> f64 {
    const TINY: f64 = 1.0e-300;
    const ONE: f64 = 1.0;
    const TWO: f64 = 2.0;
    const HUGE: f64 = 1.0e300;
    let jx = high_word(x) as i32;
    let ix = jx & 0x7FFF_FFFF;

    if ix >= 0x7FF0_0000 {
        return if jx >= 0 { ONE / x + ONE } else { ONE / x - ONE };
    }
    let z;
    if ix < 0x4036_0000 {
        if ix < 0x3E30_0000 && HUGE + x > ONE {
            return x;
        }
        if ix >= 0x3FF0_0000 {
            let t = expm1(TWO * x.abs());
            z = ONE - TWO / (t + TWO);
        } else {
            let t = expm1(-TWO * x.abs());
            z = -t / (t + TWO);
        }
    } else {
        z = ONE - TINY;
    }
    if jx >= 0 {
        z
    } else {
        -z
    }
}

// ------------------------------------------------------------------------------------ cos (fdlibm s_cos.c)
//
// NOTE: upstream V8 can be built with V8_USE_LIBM_TRIG_FUNCTIONS (glibc's IBM sin/cos). Node's
// gyp build of V8 12.4 does NOT define it: measured against tests/fixtures/mathfns.json, Node's
// Math.cos is fdlibm's __kernel_cos/__kernel_sin/__ieee754_rem_pio2 with clang FMA contraction
// (a glibc port was tried first and disagreed on ~2 % of inputs — glibc is correctly rounded on
// exactly the inputs where Node is 0.5–0.6 ULP off).

/// Exact power-of-two scaling (`scalbn`).
fn scalbn(x: f64, n: i32) -> f64 {
    let mut y = x;
    let mut n = n;
    while n > 1000 {
        y *= f64::from_bits(0x7E70_0000_0000_0000); // 2^1000
        n -= 1000;
    }
    while n < -1000 {
        y *= f64::from_bits(0x0170_0000_0000_0000); // 2^-1000
        n += 1000;
    }
    y * f64::from_bits(((1023 + n) as u64) << 52)
}

const C1: f64 = 4.16666666666666019037e-02;
const C2: f64 = -1.38888888888741095749e-03;
const C3: f64 = 2.48015872894767294178e-05;
const C4: f64 = -2.75573143513906633035e-07;
const C5: f64 = 2.08757232129817482790e-09;
const C6: f64 = -1.13596475577881948265e-11;

/// fdlibm `__kernel_cos(x, y)` with clang's contraction.
#[inline]
fn kernel_cos(x: f64, y: f64) -> f64 {
    const ONE: f64 = 1.0;
    let ix = (high_word(x) as i32) & 0x7FFF_FFFF;
    if ix < 0x3E40_0000 && (x as i32) == 0 {
        return ONE;
    }
    let z = x * x;
    // z * (C1 + z*(C2 + z*(C3 + z*(C4 + z*(C5 + z*C6)))))
    let r = z * fma(z, fma(z, fma(z, fma(z, fma(z, C6, C5), C4), C3), C2), C1);
    if ix < 0x3FD3_3333 {
        // one - (0.5*z - (z*r - x*y))  →  one - fma(0.5, z, -fma(z, r, -(x*y)))
        ONE - fma(0.5f64, z, -fma(z, r, -(x * y)))
    } else {
        let qx = if ix > 0x3FE9_0000 { 0.28125 } else { insert_words((ix - 0x0020_0000) as u32, 0) };
        // iz = 0.5*z - qx  →  fma(0.5, z, -qx)
        let iz = fma(0.5f64, z, -qx);
        let a = ONE - qx;
        // a - (iz - (z*r - x*y))
        a - (iz - fma(z, r, -(x * y)))
    }
}

const KS1: f64 = -1.66666666666666324348e-01;
const KS2: f64 = 8.33333333332248946124e-03;
const KS3: f64 = -1.98412698298579493134e-04;
const KS4: f64 = 2.75573137070700676789e-06;
const KS5: f64 = -2.50507602534068634195e-08;
const KS6: f64 = 1.58969099521155010221e-10;

/// fdlibm `__kernel_sin(x, y, iy)` with clang's contraction.
#[inline]
fn kernel_sin(x: f64, y: f64, iy: i32) -> f64 {
    const HALF: f64 = 0.5;
    let ix = (high_word(x) as i32) & 0x7FFF_FFFF;
    if ix < 0x3E40_0000 && (x as i32) == 0 {
        return x;
    }
    let z = x * x;
    let v = z * x;
    // S2 + z*(S3 + z*(S4 + z*(S5 + z*S6)))
    let r = fma(z, fma(z, fma(z, fma(z, KS6, KS5), KS4), KS3), KS2);
    if iy == 0 {
        // x + v*(S1 + z*r)  →  fma(v, fma(z, r, S1), x)
        fma(v, fma(z, r, KS1), x)
    } else {
        // x - ((z*(half*y - v*r) - y) - v*S1)
        //   →  x - fma(-v, S1, fma(z, fma(half, y, -(v*r)), -y))
        x - fma(-v, KS1, fma(z, fma(HALF, y, -(v * r)), -y))
    }
}

const TWO_OVER_PI: [i32; 66] = [
    0xA2F983, 0x6E4E44, 0x1529FC, 0x2757D1, 0xF534DD, 0xC0DB62, 0x95993C, 0x439041, 0xFE5163, 0xABDEBB, 0xC561B7,
    0x246E3A, 0x424DD2, 0xE00649, 0x2EEA09, 0xD1921C, 0xFE1DEB, 0x1CB129, 0xA73EE8, 0x8235F5, 0x2EBB44, 0x84E99C,
    0x7026B4, 0x5F7E41, 0x3991D6, 0x398353, 0x39F49C, 0x845F8B, 0xBDF928, 0x3B1FF8, 0x97FFDE, 0x05980F, 0xEF2F11,
    0x8B5A0A, 0x6D1F6D, 0x367ECF, 0x27CB09, 0xB74F46, 0x3F669E, 0x5FEA2D, 0x7527BA, 0xC7EBE5, 0xF17B3D, 0x0739F7,
    0x8A5292, 0xEA6BFB, 0x5FB11F, 0x8D5D08, 0x560330, 0x46FC7B, 0x6BABF0, 0xCFBC20, 0x9AF436, 0x1DA9E3, 0x91615E,
    0xE61B08, 0x659985, 0x5F14A0, 0x68408D, 0xFFD880, 0x4D7327, 0x310606, 0x1556CA, 0x73A8C9, 0x60E27B, 0xC08C6B,
];

const NPIO2_HW: [i32; 32] = [
    0x3FF921FB, 0x400921FB, 0x4012D97C, 0x401921FB, 0x401F6A7A, 0x4022D97C, 0x4025FDBB, 0x402921FB, 0x402C463A,
    0x402F6A7A, 0x4031475C, 0x4032D97C, 0x40346B9C, 0x4035FDBB, 0x40378FDB, 0x403921FB, 0x403AB41B, 0x403C463A,
    0x403DD85A, 0x403F6A7A, 0x40407E4C, 0x4041475C, 0x4042106C, 0x4042D97C, 0x4043A28C, 0x40446B9C, 0x404534AC,
    0x4045FDBB, 0x4046C6CB, 0x40478FDB, 0x404858EB, 0x404921FB,
];

const PIO2: [f64; 8] = [
    1.57079625129699707031e+00,
    7.54978941586159635335e-08,
    5.39030252995776476554e-15,
    3.28200341580791294123e-22,
    1.27065575308067607349e-29,
    1.22933308981111328932e-36,
    2.73370053816464559624e-44,
    2.16741683877804819444e-51,
];

/// fdlibm `__kernel_rem_pio2(x, y, e0, nx, prec=2, two_over_pi)` with clang's contraction.
/// Only reached for |x| > 2^19·π/2 (never by the engine, whose arguments are < 2π).
fn kernel_rem_pio2(x: &[f64], y: &mut [f64; 2], e0: i32, nx: usize, prec: usize) -> i32 {
    const INIT_JK: [usize; 4] = [2, 3, 4, 6];
    const ZERO: f64 = 0.0;
    const ONE: f64 = 1.0;
    const TWO24: f64 = 1.67772160000000000000e+07;
    const TWON24: f64 = 5.96046447753906250000e-08;

    let mut iq = [0i32; 20];
    let mut f = [0.0f64; 20];
    let mut fq = [0.0f64; 20];
    let mut q = [0.0f64; 20];

    let jk = INIT_JK[prec];
    let jp = jk;

    let jx = nx as i32 - 1;
    let mut jv = (e0 - 3) / 24;
    if jv < 0 {
        jv = 0;
    }
    let mut q0 = e0 - 24 * (jv + 1);

    let mut j = jv - jx;
    let m = jx + jk as i32;
    for i in 0..=m {
        f[i as usize] = if j < 0 { ZERO } else { TWO_OVER_PI[j as usize] as f64 };
        j += 1;
    }

    for i in 0..=jk {
        let mut fw = 0.0f64;
        for j in 0..=jx as usize {
            // fw += x[j] * f[jx+i-j]  →  fma
            fw = fma(x[j], f[jx as usize + i - j], fw);
        }
        q[i] = fw;
    }

    let mut jz = jk as i32;
    let mut z;
    let mut n;
    let mut ih;
    loop {
        // distill q[] into iq[] reversingly
        z = q[jz as usize];
        let mut i = 0usize;
        let mut j = jz;
        while j > 0 {
            let fw = ((TWON24 * z) as i32) as f64;
            // iq[i] = (int32)(z - two24*fw)  →  fma(-two24, fw, z)
            iq[i] = fma(-TWO24, fw, z) as i32;
            z = q[(j - 1) as usize] + fw;
            i += 1;
            j -= 1;
        }

        z = scalbn(z, q0);
        // z -= 8.0*floor(z*0.125)  →  fma(-8.0, floor(z*0.125), z)
        z = fma(-8.0f64, (z * 0.125).floor(), z);
        n = z as i32;
        z -= n as f64;
        ih = 0;
        if q0 > 0 {
            let i = iq[(jz - 1) as usize] >> (24 - q0);
            n += i;
            iq[(jz - 1) as usize] -= i << (24 - q0);
            ih = iq[(jz - 1) as usize] >> (23 - q0);
        } else if q0 == 0 {
            ih = iq[(jz - 1) as usize] >> 23;
        } else if z >= 0.5 {
            ih = 2;
        }

        if ih > 0 {
            n += 1;
            let mut carry = 0;
            for i in 0..jz as usize {
                let j = iq[i];
                if carry == 0 {
                    if j != 0 {
                        carry = 1;
                        iq[i] = 0x100_0000 - j;
                    }
                } else {
                    iq[i] = 0xFF_FFFF - j;
                }
            }
            if q0 > 0 {
                match q0 {
                    1 => iq[(jz - 1) as usize] &= 0x7F_FFFF,
                    2 => iq[(jz - 1) as usize] &= 0x3F_FFFF,
                    _ => {}
                }
            }
            if ih == 2 {
                z = ONE - z;
                if carry != 0 {
                    z -= scalbn(ONE, q0);
                }
            }
        }

        // check if recomputation is needed
        if z == ZERO {
            let mut j = 0;
            let mut i = jz - 1;
            while i >= jk as i32 {
                j |= iq[i as usize];
                i -= 1;
            }
            if j == 0 {
                let mut k = 1usize;
                while jk >= k && iq[jk - k] == 0 {
                    k += 1;
                }
                for i in (jz + 1) as usize..=(jz as usize + k) {
                    f[jx as usize + i] = TWO_OVER_PI[jv as usize + i] as f64;
                    let mut fw = 0.0f64;
                    for j in 0..=jx as usize {
                        // fw += x[j] * f[jx+i-j]  →  fma (recomputation branch, same as above)
                        fw = fma(x[j], f[jx as usize + i - j], fw);
                    }
                    q[i] = fw;
                }
                jz += k as i32;
                continue;
            }
        }
        break;
    }

    // chop off zero terms
    if z == 0.0 {
        jz -= 1;
        q0 -= 24;
        while iq[jz as usize] == 0 {
            jz -= 1;
            q0 -= 24;
        }
    } else {
        z = scalbn(z, -q0);
        if z >= TWO24 {
            let fw = ((TWON24 * z) as i32) as f64;
            // iq[jz] = (int32)(z - two24*fw)  →  fma(-two24, fw, z)
            iq[jz as usize] = fma(-TWO24, fw, z) as i32;
            jz += 1;
            q0 += 24;
            iq[jz as usize] = fw as i32;
        } else {
            iq[jz as usize] = z as i32;
        }
    }

    // convert integer "bit" chunk to floating-point value
    let mut fw = scalbn(ONE, q0);
    let mut i = jz;
    while i >= 0 {
        q[i as usize] = fw * iq[i as usize] as f64;
        fw *= TWON24;
        i -= 1;
    }

    // compute PIo2[0,...,jp]*q[jz,...,0]
    let mut i = jz;
    while i >= 0 {
        let mut fw = 0.0f64;
        let mut k = 0usize;
        while k <= jp && (k as i32) <= jz - i {
            // fw += PIo2[k] * q[i+k]  →  fma
            fw = fma(PIO2[k], q[(i + k as i32) as usize], fw);
            k += 1;
        }
        fq[(jz - i) as usize] = fw;
        i -= 1;
    }

    // compress fq[] into y[] (prec 2)
    let mut fw = 0.0f64;
    let mut i = jz;
    while i >= 0 {
        fw += fq[i as usize];
        i -= 1;
    }
    y[0] = if ih == 0 { fw } else { -fw };
    let mut fw = fq[0] - fw;
    for i in 1..=jz as usize {
        fw += fq[i];
    }
    y[1] = if ih == 0 { fw } else { -fw };
    n & 7
}

/// fdlibm `__ieee754_rem_pio2(x, y)` with clang's contraction.
fn rem_pio2(x: f64, y: &mut [f64; 2]) -> i32 {
    const ZERO: f64 = 0.0;
    const HALF: f64 = 0.5;
    const TWO24: f64 = 1.67772160000000000000e+07;
    const INVPIO2: f64 = 6.36619772367581382433e-01;
    const PIO2_1: f64 = 1.57079632673412561417e+00;
    const PIO2_1T: f64 = 6.07710050650619224932e-11;
    const PIO2_2: f64 = 6.07710050630396597660e-11;
    const PIO2_2T: f64 = 2.02226624879595063154e-21;
    const PIO2_3: f64 = 2.02226624871116645580e-21;
    const PIO2_3T: f64 = 8.47842766036889956997e-32;

    let hx = high_word(x) as i32;
    let ix = hx & 0x7FFF_FFFF;
    if ix <= 0x3FE9_21FB {
        y[0] = x;
        y[1] = 0.0;
        return 0;
    }
    if ix < 0x4002_D97C {
        if hx > 0 {
            let mut z = x - PIO2_1;
            if ix != 0x3FF9_21FB {
                y[0] = z - PIO2_1T;
                y[1] = (z - y[0]) - PIO2_1T;
            } else {
                z -= PIO2_2;
                y[0] = z - PIO2_2T;
                y[1] = (z - y[0]) - PIO2_2T;
            }
            return 1;
        } else {
            let mut z = x + PIO2_1;
            if ix != 0x3FF9_21FB {
                y[0] = z + PIO2_1T;
                y[1] = (z - y[0]) + PIO2_1T;
            } else {
                z += PIO2_2;
                y[0] = z + PIO2_2T;
                y[1] = (z - y[0]) + PIO2_2T;
            }
            return -1;
        }
    }
    if ix <= 0x4139_21FB {
        let t = x.abs();
        // n = (int)(t*invpio2 + half)  →  fma
        let n = fma(t, INVPIO2, HALF) as i32;
        let fn_ = n as f64;
        // r = t - fn*pio2_1  →  fma(-fn, pio2_1, t)
        let mut r = fma(-fn_, PIO2_1, t);
        let mut w = fn_ * PIO2_1T;
        if n < 32 && ix != NPIO2_HW[(n - 1) as usize] {
            y[0] = r - w;
        } else {
            let j = ix >> 20;
            y[0] = r - w;
            let mut i = j - (((high_word(y[0]) >> 20) & 0x7FF) as i32);
            if i > 16 {
                let t = r;
                w = fn_ * PIO2_2;
                r = t - w;
                // w = fn*pio2_2t - ((t - r) - w)  →  fma(fn, pio2_2t, -((t-r)-w))
                w = fma(fn_, PIO2_2T, -((t - r) - w));
                y[0] = r - w;
                i = j - (((high_word(y[0]) >> 20) & 0x7FF) as i32);
                if i > 49 {
                    let t = r;
                    w = fn_ * PIO2_3;
                    r = t - w;
                    // w = fn*pio2_3t - ((t - r) - w)  →  fma(fn, pio2_3t, -((t-r)-w))
                    w = fma(fn_, PIO2_3T, -((t - r) - w));
                    y[0] = r - w;
                }
            }
        }
        y[1] = (r - y[0]) - w;
        if hx < 0 {
            y[0] = -y[0];
            y[1] = -y[1];
            return -n;
        }
        return n;
    }
    if ix >= 0x7FF0_0000 {
        y[0] = x - x;
        y[1] = y[0];
        return 0;
    }
    // large arguments: z = scalbn(|x|, ilogb(x) - 23)
    let low = low_word(x);
    let e0 = (ix >> 20) - 1046;
    let mut z = insert_words((ix - (e0 << 20)) as u32, low);
    let mut tx = [0.0f64; 3];
    for t in tx.iter_mut().take(2) {
        *t = (z as i32) as f64;
        z = (z - *t) * TWO24;
    }
    tx[2] = z;
    let mut nx = 3usize;
    while tx[nx - 1] == ZERO {
        nx -= 1;
    }
    let n = kernel_rem_pio2(&tx, y, e0, nx, 2);
    if hx < 0 {
        y[0] = -y[0];
        y[1] = -y[1];
        return -n;
    }
    n
}

/// fdlibm `cos(x)` as V8's `base::ieee754::cos` (Node 22 build), clang-contracted.
pub fn cos(x: f64) -> f64 {
    let ix = (high_word(x) as i32) & 0x7FFF_FFFF;
    if ix <= 0x3FE9_21FB {
        kernel_cos(x, 0.0)
    } else if ix >= 0x7FF0_0000 {
        x - x
    } else {
        let mut y = [0.0f64; 2];
        let n = rem_pio2(x, &mut y);
        match n & 3 {
            0 => kernel_cos(y[0], y[1]),
            1 => -kernel_sin(y[0], y[1], 1),
            2 => -kernel_cos(y[0], y[1]),
            _ => kernel_sin(y[0], y[1], 1),
        }
    }
}

/// fdlibm `sin(x)` (companion; not used by the engine).
pub fn sin(x: f64) -> f64 {
    let ix = (high_word(x) as i32) & 0x7FFF_FFFF;
    if ix <= 0x3FE9_21FB {
        kernel_sin(x, 0.0, 0)
    } else if ix >= 0x7FF0_0000 {
        x - x
    } else {
        let mut y = [0.0f64; 2];
        let n = rem_pio2(x, &mut y);
        match n & 3 {
            0 => kernel_sin(y[0], y[1], 1),
            1 => kernel_cos(y[0], y[1]),
            2 => -kernel_sin(y[0], y[1], 1),
            _ => -kernel_cos(y[0], y[1]),
        }
    }
}
