#!/usr/bin/env -S npx tsx
/**
 * Compute the FlyWire manifestHash OFFLINE (no chain commit).
 *
 * Assembles the manifest that WOULD be committed when FLYWIRE_TOPOLOGY=true,
 * computes sha256(canonical(manifest)), and prints the hash. Does NOT commit.
 *
 * Usage: npx tsx scripts/_compute-flywire-hash.ts
 */
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";
import { createHash } from "node:crypto";

import {
  BRAIN_MANIFEST_VERSION,
  FLYWIRE_PROVENANCE,
  LIF_CONSTANTS,
  NEURON_BASE_PARAMS,
  NEURON_JITTER,
  connectomeSpecForSeedFlyWire,
  flyWireManifestConnectome,
  decodePayload,
  DEFAULT_DECODER_CONFIG,
  type FlyWireSubgraph,
} from "@fly/fly-brain";

// Mirror the trader-worker's provenance helpers (canonical + sha256)
function canonical(value: unknown): string {
  return JSON.stringify(value, (_k, v) =>
    v !== null && typeof v === "object" && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v).sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0)))
      : v
  );
}

function sha256Hex(value: unknown): string {
  return createHash("sha256").update(canonical(value)).digest("hex");
}

const here = dirname(fileURLToPath(import.meta.url));
const ARTIFACT_PATH = join(here, "..", "packages", "fly-brain", "src", "connectome-data", "fafb783-mb-cx.bin.gz.b64");

// Production config (from wrangler.toml)
const POPULATION_SIZE = 24;
const SEED_BASE = 42;
const SEED_STRIDE = 7919;
const CHAIN_ID = 5042; // Arc mainnet
const REGIME_HOT = 0.66;
const REGIME_COLD = 0.33;

function loadSubgraph(): FlyWireSubgraph {
  const b64 = readFileSync(ARTIFACT_PATH, "utf-8").trim();
  const compressed = Buffer.from(b64, "base64");
  const raw = new Uint8Array(gunzipSync(compressed));
  return decodePayload(raw);
}

function main(): void {
  console.log("=== FlyWire manifestHash computation (OFFLINE, no chain commit) ===\n");

  const t0 = performance.now();
  const subgraph = loadSubgraph();
  console.log(`  subgraph loaded: ${subgraph.nNeurons} neurons, ${subgraph.nEdges} synapses`);

  // Assemble per-fly structural specs
  const flies: { id: number; seed: number; structural: unknown }[] = [];
  for (let i = 0; i < POPULATION_SIZE; i++) {
    const seed = (SEED_BASE + i * SEED_STRIDE) >>> 0;
    const structural = connectomeSpecForSeedFlyWire(seed, subgraph);
    flies.push({ id: i, seed, structural });
    if (i < 3 || i === POPULATION_SIZE - 1) {
      console.log(`  fly #${String(i).padStart(2, "0")} seed ${String(seed).padStart(10)} → ${structural.neuronCount}n/${structural.synapseCount}s edgeHash ${structural.edgeHash}`);
    } else if (i === 3) {
      console.log(`  ... (${POPULATION_SIZE - 4} more)`);
    }
  }
  const tSpecs = performance.now();
  console.log(`  structural specs computed in ${((tSpecs - t0) / 1000).toFixed(1)}s`);

  // Assemble the full manifest (mirrors trader-worker/src/manifest.ts assembleManifest)
  const manifest = {
    v: 1, // MANIFEST_SCHEMA_VERSION
    schema: "murmur-brain-manifest",
    brainManifestVersion: BRAIN_MANIFEST_VERSION,
    proofV: 1, // PROOF_VERSION
    policy: "econ-v1", // POLICY_VERSION
    codeVersion: null,
    chainId: CHAIN_ID,
    chainTag: "arc-mainnet",
    population: {
      size: POPULATION_SIZE,
      seedBase: SEED_BASE,
      seedStride: SEED_STRIDE,
      seedFormula: "seed[i] = (seedBase + i * seedStride) >>> 0",
    },
    connectome: flyWireManifestConnectome(),
    lif: LIF_CONSTANTS,
    neuronBaseParams: NEURON_BASE_PARAMS,
    neuronJitter: NEURON_JITTER,
    decoder: {
      ...DEFAULT_DECODER_CONFIG,
      hotT: REGIME_HOT,
      coldT: REGIME_COLD,
    },
    provenance: FLYWIRE_PROVENANCE,
    llm: {
      used: false,
      statement:
        "No large-language model is used in perception, decision-making or settlement. Behaviour emerges from a spiking leaky-integrate-and-fire connectome built from REAL FAFB 783 FlyWire data (CC-BY 4.0); each trade is a deterministic read-out of decoded motor drives under policy econ-v1. This manifest is generated by pure code from the committed seeds and is reproducible offline by anyone.",
    },
    flies,
  };

  const hash = sha256Hex(manifest);
  const tHash = performance.now();

  console.log(`\n${"=".repeat(72)}`);
  console.log(`  FlyWire manifestHash (FLYWIRE_TOPOLOGY=true):`);
  console.log(`  0x${hash}`);
  console.log(`${"=".repeat(72)}`);
  console.log(`  Current production hash (flag OFF):`);
  console.log(`  0xbbafeaa0a187f5b12e98ed40284e5d49f91fc9a2b718e5e777ab40128fafafa7`);
  console.log(`${"=".repeat(72)}`);
  console.log(`  Hash differs: ${hash !== "bbafeaa0a187f5b12e98ed40284e5d49f91fc9a2b718e5e777ab40128fafafa7" ? "YES (expected — topology change rotates the hash)" : "NO (unexpected!)"}`);
  console.log(`  Timing: specs ${((tSpecs - t0) / 1000).toFixed(1)}s, hash ${((tHash - tSpecs) / 1000).toFixed(2)}s`);
  console.log(`\n  *** NOT COMMITTED ON-CHAIN — awaiting user approval ***`);
  console.log(`  *** To commit: CHAIN_ID=5042 MANIFEST_CONFIRM=1 APPROVED_HASH=0x${hash} node scripts/commit-manifest.mjs ***`);
}

main();
